import type { ProfileFieldDefinition } from '@/types/gospel';

export const PROFILE_FIELDS: ProfileFieldDefinition[] = [
  // Badge requirements
  {
    name: 'service_times',
    label: 'Service times',
    hint: 'Which days and times do you meet? This helps visitors plan their first visit.',
    category: 'badge',
    points: 10,
    type: 'service-times',
    validation: { min: 1, max: 10 },
  },
  {
    name: 'address',
    label: 'Address',
    hint: 'Your physical address so visitors can find you.',
    category: 'badge',
    points: 10,
    type: 'address',
  },
  {
    name: 'phone',
    label: 'Phone',
    hint: 'A contact number with country code, for example +46701234567.',
    placeholder: '+34 612 345 678',
    category: 'badge',
    points: 10,
    type: 'tel',
    validation: { pattern: '^\\+[0-9]{7,15}$' },
  },
  {
    name: 'contact_email',
    label: 'Contact email',
    hint: 'An email address visitors and newcomers can use to reach you.',
    placeholder: 'hello@yourchurch.org',
    category: 'badge',
    points: 10,
    type: 'email',
    validation: { maxLength: 254 },
  },
  // Bonus
  {
    name: 'description',
    label: 'About your church',
    hint: 'Use this to explain who you are as a church: your mission, culture, theology, and the kind of community you are building.',
    placeholder: 'We are a gospel-centered church in central Madrid focused on worship, Bible teaching, prayer, and community for people of all ages.',
    category: 'bonus',
    points: 10,
    type: 'textarea',
    validation: { minLength: 80, maxLength: 500 },
  },
  {
    name: 'pastor',
    label: 'Pastor / leader',
    hint: 'Who leads your church? Add a name and title, for example Senior Pastor.',
    category: 'bonus',
    points: 0,
    type: 'pastor',
    validation: { minLength: 2, maxLength: 100 },
  },
  {
    name: 'what_to_expect',
    label: 'What a first visit feels like',
    hint: 'Use this for practical first-visit details like service length, worship style, dress, kids, language, parking, and what happens after the service.',
    placeholder: 'A typical Sunday lasts about 90 minutes with live worship, a Bible message, prayer, and coffee afterwards. Dress is casual and kids check-in opens 15 minutes before the service.',
    category: 'bonus',
    points: 0,
    type: 'textarea',
    validation: { minLength: 30, maxLength: 500 },
  },
  {
    name: 'livestream_url',
    label: 'Livestream',
    hint: 'A link to your livestream so people can watch online.',
    placeholder: 'https://youtube.com/@yourchurch/live',
    category: 'bonus',
    points: 0,
    type: 'url',
    validation: { maxLength: 500 },
  },
  {
    name: 'giving_url',
    label: 'Giving / donate',
    hint: 'A link to your online giving page.',
    placeholder: 'https://yourchurch.org/give',
    category: 'bonus',
    points: 0,
    type: 'url',
    validation: { maxLength: 500 },
  },
  {
    name: 'instagram_url',
    label: 'Instagram',
    hint: 'Your Instagram profile or @handle.',
    placeholder: '@yourchurch or https://instagram.com/yourchurch',
    category: 'bonus',
    points: 0,
    type: 'url',
    validation: { maxLength: 200 },
  },
  {
    name: 'facebook_url',
    label: 'Facebook',
    hint: 'A link to your Facebook page.',
    placeholder: 'https://facebook.com/yourchurch',
    category: 'bonus',
    points: 0,
    type: 'url',
    validation: { maxLength: 500 },
  },
  {
    name: 'youtube_url',
    label: 'YouTube',
    hint: 'A link to your YouTube channel.',
    placeholder: 'https://youtube.com/@yourchurch',
    category: 'bonus',
    points: 0,
    type: 'url',
    validation: { maxLength: 300 },
  },
  {
    name: 'website_url',
    label: 'Website',
    hint: 'Your official website.',
    placeholder: 'https://yourchurch.org',
    category: 'bonus',
    points: 7,
    type: 'url',
    validation: { maxLength: 500 },
  },
  {
    name: 'rss_feed_url',
    label: 'RSS feed',
    hint: 'An RSS link for showing your latest news or sermons.',
    placeholder: 'https://yourchurch.org/feed.xml',
    category: 'bonus',
    points: 0,
    type: 'url',
    validation: { maxLength: 500 },
  },
  {
    name: 'denomination',
    label: 'Denomination',
    hint: 'Which denomination or network are you part of?',
    category: 'bonus',
    points: 8,
    type: 'select',
    options: ['Pingst', 'EFK', 'Equmenia', 'Svenska kyrkan', 'Katolska', 'Vineyard', 'Trosrörelsen', 'Frälsningsarmén', 'Baptistsamfundet', 'Annat'],
    validation: { maxLength: 100 },
  },
  {
    name: 'languages',
    label: 'Languages',
    hint: 'Which languages are spoken during your services?',
    category: 'bonus',
    points: 7,
    type: 'multi-select',
    options: [
      'Svenska',
      'Engelska',
      'Spanska',
      'Tyska',
      'Franska',
      'Portugisiska',
      'Italienska',
      'Nederländska',
      'Polska',
      'Rumänska',
      'Ukrainska',
      'Ryska',
      'Koreanska',
      'Kinesiska',
      'Turkiska',
      'Tagalog',
      'Arabiska',
      'Farsi',
      'Tigrinja',
      'Finska',
      'Annat',
    ],
    validation: { min: 1, max: 10 },
  },
  // Extra
  {
    name: 'logo_url',
    label: 'Logo',
    hint: 'Your logo is shown on the church page and in search results. Paste an image URL or upload a file.',
    placeholder: 'https://yourchurch.org/logo.png',
    category: 'extra',
    points: 8,
    type: 'image',
  },
  {
    name: 'cover_image_url',
    label: 'Hero image',
    hint: 'The large header image at the top of your church page. Paste an image URL or upload a file.',
    placeholder: 'https://yourchurch.org/hero.jpg',
    category: 'extra',
    points: 0,
    type: 'image',
  },
  {
    name: 'ministries',
    label: 'Ministries',
    hint: 'Which ministries do you offer? This helps visitors understand where they fit.',
    category: 'extra',
    points: 7,
    type: 'checkboxes',
    options: ['Barnverksamhet', 'Ungdom', 'Kör/lovsång', 'Bönegrupp', 'Alphakurs', 'Bibelstudium', 'Diakoni', 'Internationellt', 'Annat'],
    validation: { max: 15 },
  },
  {
    name: 'church_size',
    label: 'Church size',
    hint: 'Roughly how many people attend a typical service?',
    category: 'extra',
    points: 5,
    type: 'select',
    options: ['small', 'medium', 'large', 'mega'],
  },
];

export const SOCIAL_MEDIA_FIELDS = ['instagram_url', 'facebook_url', 'youtube_url'];
export const SOCIAL_MEDIA_POINTS = 8;

export const CONTACT_FIELDS = ['phone', 'contact_email'];

export const PROFILE_OPTION_LABELS: Record<string, string> = {
  Pingst: 'Pentecostal',
  EFK: 'EFK',
  Equmenia: 'Equmenia',
  'Svenska kyrkan': 'Church of Sweden',
  Katolska: 'Catholic',
  Vineyard: 'Vineyard',
  Trosrörelsen: 'Word of Faith',
  Frälsningsarmén: 'Salvation Army',
  Baptistsamfundet: 'Baptist',
  Annat: 'Other',
  Karismatisk: 'Charismatic',
  Liturgisk: 'Liturgical',
  Evangelikal: 'Evangelical',
  Reformert: 'Reformed',
  Svenska: 'Swedish',
  Engelska: 'English',
  Spanska: 'Spanish',
  Tyska: 'German',
  Portugisiska: 'Portuguese',
  Italienska: 'Italian',
  Nederländska: 'Dutch',
  Polska: 'Polish',
  Rumänska: 'Romanian',
  Ukrainska: 'Ukrainian',
  Ryska: 'Russian',
  Koreanska: 'Korean',
  Kinesiska: 'Chinese',
  Turkiska: 'Turkish',
  Tagalog: 'Tagalog',
  Arabiska: 'Arabic',
  Farsi: 'Farsi',
  Tigrinja: 'Tigrinya',
  Franska: 'French',
  Finska: 'Finnish',
  Barnverksamhet: 'Children',
  Ungdom: 'Youth',
  'Kör/lovsång': 'Choir / worship',
  Bönegrupp: 'Prayer group',
  Alphakurs: 'Alpha course',
  Bibelstudium: 'Bible study',
  Diakoni: 'Outreach / care',
  Internationellt: 'International',
  Måndag: 'Monday',
  Tisdag: 'Tuesday',
  Onsdag: 'Wednesday',
  Torsdag: 'Thursday',
  Fredag: 'Friday',
  Lördag: 'Saturday',
  Söndag: 'Sunday',
};

export function getProfileOptionLabel(value: string): string {
  return PROFILE_OPTION_LABELS[value] ?? value;
}

export const DENOMINATION_OPTIONS = PROFILE_FIELDS.find(f => f.name === 'denomination')!.options!;
export const CHURCH_SIZE_LABELS: Record<string, string> = {
  small: 'Under 100 attendees',
  medium: '100-300 attendees',
  large: '300-1000 attendees',
  mega: 'Over 1000 attendees',
};

export const DAY_OPTIONS = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'];
