import type { ProfileFieldDefinition } from '@/types/gospel';

export const PROFILE_FIELDS: ProfileFieldDefinition[] = [
  // Badge requirements
  {
    name: 'service_times',
    label: 'Gudstjänsttider',
    hint: 'Vilka dagar och tider har ni gudstjänst? Hjälper besökare planera sitt besök.',
    category: 'badge',
    points: 10,
    type: 'service-times',
    validation: { min: 1, max: 10 },
  },
  {
    name: 'address',
    label: 'Adress',
    hint: 'Er fysiska adress så besökare hittar till er.',
    category: 'badge',
    points: 10,
    type: 'address',
  },
  {
    name: 'phone',
    label: 'Telefon',
    hint: 'Kontaktnummer med landskod, t.ex. +46701234567.',
    category: 'badge',
    points: 10,
    type: 'tel',
    validation: { pattern: '^\\+[0-9]{7,15}$' },
  },
  {
    name: 'contact_email',
    label: 'Kontakt-epost',
    hint: 'E-post dit besökare och intresserade kan höra av sig.',
    category: 'badge',
    points: 10,
    type: 'email',
    validation: { maxLength: 254 },
  },
  // Bonus
  {
    name: 'description',
    label: 'Beskrivning',
    hint: 'Det första besökare läser om er kyrka. Beskriv vad som gör er unika.',
    category: 'bonus',
    points: 10,
    type: 'textarea',
    validation: { minLength: 80, maxLength: 500 },
  },
  {
    name: 'pastor',
    label: 'Pastor / ledare',
    hint: 'Vem leder er kyrka? Namn och titel (t.ex. Senior Pastor).',
    category: 'bonus',
    points: 0,
    type: 'pastor',
    validation: { minLength: 2, maxLength: 100 },
  },
  {
    name: 'what_to_expect',
    label: 'Vad kan jag förvänta mig?',
    hint: 'Beskriv kort hur en gudstjänst ser ut - hjälper förstagångsbesökare våga komma.',
    category: 'bonus',
    points: 0,
    type: 'textarea',
    validation: { minLength: 30, maxLength: 500 },
  },
  {
    name: 'livestream_url',
    label: 'Livestream',
    hint: 'Länk till er livestream så besökare kan titta online.',
    category: 'bonus',
    points: 0,
    type: 'url',
    validation: { maxLength: 500 },
  },
  {
    name: 'giving_url',
    label: 'Ge / Donera',
    hint: 'Länk till er online-givande (t.ex. Swish-sida, kortbetalning).',
    category: 'bonus',
    points: 0,
    type: 'url',
    validation: { maxLength: 500 },
  },
  {
    name: 'instagram_url',
    label: 'Instagram',
    hint: 'Er Instagram-profil eller @-handle.',
    category: 'bonus',
    points: 0,
    type: 'url',
    validation: { maxLength: 200 },
  },
  {
    name: 'facebook_url',
    label: 'Facebook',
    hint: 'Länk till er Facebook-sida.',
    category: 'bonus',
    points: 0,
    type: 'url',
    validation: { maxLength: 500 },
  },
  {
    name: 'youtube_url',
    label: 'YouTube',
    hint: 'Länk till er YouTube-kanal.',
    category: 'bonus',
    points: 0,
    type: 'url',
    validation: { maxLength: 300 },
  },
  {
    name: 'website_url',
    label: 'Hemsida',
    hint: 'Er officiella hemsida.',
    category: 'bonus',
    points: 7,
    type: 'url',
    validation: { maxLength: 500 },
  },
  {
    name: 'rss_feed_url',
    label: 'RSS-flöde',
    hint: 'RSS-länk för att visa era senaste nyheter/predikningar på sidan.',
    category: 'bonus',
    points: 0,
    type: 'url',
    validation: { maxLength: 500 },
  },
  {
    name: 'google_news_query',
    label: 'Google News-sökning',
    hint: 'Sökord för att visa nyheter om er kyrka (t.ex. "Livets Ord Uppsala").',
    category: 'extra',
    points: 0,
    type: 'text',
    validation: { minLength: 3, maxLength: 160 },
  },
  {
    name: 'denomination',
    label: 'Samfund',
    hint: 'Vilket samfund eller nätverk tillhör ni?',
    category: 'bonus',
    points: 8,
    type: 'select',
    options: ['Pingst', 'EFK', 'Equmenia', 'Svenska kyrkan', 'Katolska', 'Vineyard', 'Trosrörelsen', 'Frälsningsarmén', 'Baptistsamfundet', 'Annat'],
    validation: { maxLength: 100 },
  },
  {
    name: 'theological_orientation',
    label: 'Teologisk inriktning',
    hint: 'Hur skulle ni beskriva er teologiska profil?',
    category: 'bonus',
    points: 0,
    type: 'select',
    options: ['Karismatisk', 'Liturgisk', 'Evangelikal', 'Reformert', 'Annat'],
  },
  {
    name: 'languages',
    label: 'Språk',
    hint: 'Vilka språk talas under era gudstjänster?',
    category: 'bonus',
    points: 7,
    type: 'multi-select',
    options: ['Svenska', 'Engelska', 'Spanska', 'Arabiska', 'Farsi', 'Tigrinja', 'Franska', 'Finska', 'Annat'],
    validation: { min: 1, max: 10 },
  },
  // Extra
  {
    name: 'logo_url',
    label: 'Logotyp',
    hint: 'Er logotyp visas på kyrksidan och i sökresultat.',
    category: 'extra',
    points: 8,
    type: 'image',
  },
  {
    name: 'ministries',
    label: 'Verksamheter',
    hint: 'Vilka verksamheter erbjuder ni? Hjälper besökare hitta rätt.',
    category: 'extra',
    points: 7,
    type: 'checkboxes',
    options: ['Barnverksamhet', 'Ungdom', 'Kör/lovsång', 'Bönegrupp', 'Alphakurs', 'Bibelstudium', 'Diakoni', 'Internationellt', 'Annat'],
    validation: { max: 15 },
  },
  {
    name: 'church_size',
    label: 'Kyrkstorlek',
    hint: 'Ungefär hur många besöker en vanlig gudstjänst?',
    category: 'extra',
    points: 5,
    type: 'select',
    options: ['small', 'medium', 'large', 'mega'],
  },
];

export const SOCIAL_MEDIA_FIELDS = ['instagram_url', 'facebook_url', 'youtube_url'];
export const SOCIAL_MEDIA_POINTS = 8;

export const CONTACT_FIELDS = ['phone', 'contact_email'];

export const DENOMINATION_OPTIONS = PROFILE_FIELDS.find(f => f.name === 'denomination')!.options!;
export const CHURCH_SIZE_LABELS: Record<string, string> = {
  small: 'Under 100 besökare',
  medium: '100–300 besökare',
  large: '300–1000 besökare',
  mega: 'Över 1000 besökare',
};

export const DAY_OPTIONS = ['Måndag', 'Tisdag', 'Onsdag', 'Torsdag', 'Fredag', 'Lördag', 'Söndag'];
